In [1]:
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
drout=pd.read_csv("D:/dataset.csv",sep=";")
drout

Marital status  Application mode  Application order  Course  \
0                  1                 8                  5       2   
1                  1                 6                  1      11   
2                  1                 1                  5       5   
3                  1                 8                  2      15   
4                  2                12                  1       3   
...              ...               ...                ...     ...   
4419               1                 1                  6      15   
4420               1                 1                  2      15   
4421               1                 1                  1      12   
4422               1                 1                  1       9   
4423               1                 5                  1      15   

      Daytime/evening attendance  Previous qualification  Nacionality  \
0                              1                       1            1   
1                              1                       1            1   
2                              1                       1            1   
3                              1                       1            1   
4                              0                       1            1   
...                          ...                     ...          ...   
4419                           1                       1            1   
4420                           1                       1           19   
4421                           1                       1            1   
4422                           1                       1            1   
4423                           1                       1            9   

      Mother's qualification  Father's qualification  Mother's occupation  \
0                         13                      10                    6   
1                          1                       3                    4   
2                         22                      27                   10   
3                         23                      27                    6   
4                         22                      28                   10   
...                      ...                     ...                  ...   
4419                       1                       1                    6   
4420                       1                       1                   10   
4421                      22                      27                   10   
4422                      22                      27                    8   
4423                      23                      27                    6   

      ...  Curricular units 2nd sem (credited)  \
0     ...                                    0   
1     ...                                    0   
2     ...                                    0   
3     ...                                    0   
4     ...                                    0   
...   ...                                  ...   
4419  ...                                    0   
4420  ...                                    0   
4421  ...                                    0   
4422  ...                                    0   
4423  ...                                    0   

      Curricular units 2nd sem (enrolled)  \
0                                       0   
1                                       6   
2                                       6   
3                                       6   
4                                       6   
...                                   ...   
4419                                    6   
4420                                    6   
4421                                    8   
4422                                    5   
4423                                    6   

      Curricular units 2nd sem (evaluations)  \
0                                          0   
1                                          6   
2                                          0   
3                                        

In [2]:
x=drout.iloc[:,:34].values

In [3]:
x

array([[ 1.  ,  8.  ,  5.  , ..., 10.8 ,  1.4 ,  1.74],
       [ 1.  ,  6.  ,  1.  , ..., 13.9 , -0.3 ,  0.79],
       [ 1.  ,  1.  ,  5.  , ..., 10.8 ,  1.4 ,  1.74],
       ...,
       [ 1.  ,  1.  ,  1.  , ..., 13.9 , -0.3 ,  0.79],
       [ 1.  ,  1.  ,  1.  , ...,  9.4 , -0.8 , -3.12],
       [ 1.  ,  5.  ,  1.  , ..., 12.7 ,  3.7 , -1.7 ]])

In [4]:
y=drout.iloc[:,-1:].values

In [5]:
y

array([['Dropout'],
       ['Graduate'],
       ['Dropout'],
       ...,
       ['Dropout'],
       ['Graduate'],
       ['Graduate']], dtype=object)

In [6]:
y1=drout[['Target']]

In [7]:
y1

Target
0      Dropout
1     Graduate
2      Dropout
3     Graduate
4     Graduate
...        ...
4419  Graduate
4420   Dropout
4421   Dropout
4422  Graduate
4423  Graduate

[4424 rows x 1 columns]

In [8]:
y1['Target']

0        Dropout
1       Graduate
2        Dropout
3       Graduate
4       Graduate
          ...   
4419    Graduate
4420     Dropout
4421     Dropout
4422    Graduate
4423    Graduate
Name: Target, Length: 4424, dtype: object

In [9]:
# y3=y1[y1.Target=='Graduate' or y1.Target==' Dropout'].copy()
# y3

In [10]:
x

array([[ 1.  ,  8.  ,  5.  , ..., 10.8 ,  1.4 ,  1.74],
       [ 1.  ,  6.  ,  1.  , ..., 13.9 , -0.3 ,  0.79],
       [ 1.  ,  1.  ,  5.  , ..., 10.8 ,  1.4 ,  1.74],
       ...,
       [ 1.  ,  1.  ,  1.  , ..., 13.9 , -0.3 ,  0.79],
       [ 1.  ,  1.  ,  1.  , ...,  9.4 , -0.8 , -3.12],
       [ 1.  ,  5.  ,  1.  , ..., 12.7 ,  3.7 , -1.7 ]])

In [11]:
y=pd.get_dummies(y1,columns=['Target'],prefix=['Target'])
y

Target_Dropout  Target_Enrolled  Target_Graduate
0                  1                0                0
1                  0                0                1
2                  1                0                0
3                  0                0                1
4                  0                0                1
...              ...              ...              ...
4419               0                0                1
4420               1                0                0
4421               1                0                0
4422               0                0                1
4423               0                0                1

[4424 rows x 3 columns]

In [12]:
y.value_counts()

Target_Dropout  Target_Enrolled  Target_Graduate
0               0                1                  2209
1               0                0                  1421
0               1                0                   794
dtype: int64

In [13]:
y2=y['Target_Dropout']
y2

0       1
1       0
2       1
3       0
4       0
       ..
4419    0
4420    1
4421    1
4422    0
4423    0
Name: Target_Dropout, Length: 4424, dtype: uint8

In [14]:
X_train,X_test,y_train,y_test=train_test_split(x,y2,test_size=0.3)
cls=GaussianNB()
cls.fit(X_train,y_train)
print(X_test[0])

[ 2.          4.          1.         17.          0.         17.
  1.         25.          5.          4.          4.          0.
  0.          0.          1.          0.          0.         33.
  0.          2.          6.          7.          6.         15.33333333
  0.          0.          5.          5.          5.         15.8
  0.         11.1         0.6         2.02      ]


In [15]:
y_pred=cls.predict(X_test)
print(y_pred)

[0 1 0 ... 1 0 0]


In [16]:
from sklearn.metrics import accuracy_score
ac=accuracy_score(y_test,y_pred)
print("Accuracy:",ac) 

Accuracy: 0.8064759036144579
